export const singleTitleMapping = {
    "/index": "Dashboard",
    "/my-wallet": "My Wallet",
    "/app/my-profile": "My Profile",
    "/app/account-settings": "Account Settings",
    "/app/invoice": "Invoices",
    "/app/user-activity": "User Activity",
    "/app/my-task": "My Tasks",
    "/app/my-contact": "My Contact",
    "/app/analytics": "Analytics",
    "/app/new-project": "New Project",
    "/app/project-list": "Project List",
    "/app/project-grid": "Project Grid",
    "/app/project-details": "Project Details",
    "/app/clients-list": "Clients",      
    "/app/calendar": "My Calendar",
    "/app/inbox": "Inbox",
    "/app/chat": "Chat",
    "/app/blog": "Blog",
    "/app/filemanager": "File Manager",
    "/docs/accordion": "Accordion",
    "/docs/alerts": "Alerts",
    "/docs/avatar": "Avatar",
    "/docs/badges": "Badges",
    "/docs/breadcrumb": "Breadcrumb",
    "/docs/buttons": "Buttons",
    "/docs/cards": "Cards",
    "/docs/carousel": "Carousel",
    "/docs/collapse": "Collapse",
    "/docs/dropdowns": "Dropdowns",
    "/docs/listgroup": "List Group",
    "/docs/modal": "Modal Popup",
    "/docs/navbar": "Navbar",
    "/docs/navstabs": "Navs and Tabs",
    "/docs/offcanvas": "Offcanvas",
    "/docs/pagination": "Pagination",
    "/docs/placeholders": "Placeholders",
    "/docs/popovers": "Popovers",
    "/docs/progress": "Progress Bar",
    "/docs/spinners": "Spinners",
    "/docs/toasts": "Toasts",
    "/docs/bootstrap-icon": "Bootstrap Icon",
    "/docs/flag-icon": "Country Flags Icon",
    "/docs/fontawesome-icon": "Fontawesome Icon",
    "/docs/linear-icon": "Linear Icon",
    "/docs/weather-icon": "Weather Icon",
    "/docs/apex": "Apex Charts",
    "/docs/peity": "Peity Charts",
    "/docs/bootstrap5-tags": "Bootstrap5 Tags",
    "/docs/datatables": "Datatables",
    "/docs/flatpickr": "Flatpickr",
    "/docs/inputmask": "Inputmask",
    "/docs/jsvectormap": "Jsvectormap",
    "/docs/sortablejs": "Sortable JS",
    "/docs/sweetalert2": "Sweetalert2",
    "/docs/tagify": "Tagify",
    "/docs/tiny-slider": "Tiny Slider",
    "/docs/toast-calendar": "Toast ui Calendar",
    "/docs/toast-editor": "Toast ui Editor",
    "/docs/widgets-basic-card": "Basic Card",
    "/docs/widgets-card-tiles": "Widgets Card Tiles",
    "/docs/widgets-card-tab": "Card Tab Design",
    "/pages/table": "Tables",
    "/pages/form": "Forms",
    "/pages/pricing": "Pricing Table",
    "/pages/gallery": "Image Gallery",
    "/pages/search": "Search Page",
    "/docs/index" : "Getting Started",
    "/docs/changelog": "Changelog",
  };