export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL"
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED"
export const RESET_REGISTER_FLAG = "RESET_REGISTER_FLAG";

export const UPDATE_PROILE = 'UPDATE_PROFILE'
export const UPDATE_PROILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROILE_ERROR = 'UPDATE_PROFILE_ERROR'