export const screenMapping = {
    "/app/calendar" : "Calendar",
    "/app/inbox" : "Inbox",
    "/app/chat" : "Chat",
    "/docs/accordion" : "Accordion",
    "/docs/alerts" : "Alerts",
    "/docs/avatar" : "User Avatar",
    "/docs/badges" : "Badges",
    "/docs/breadcrumb" : "Breadcrumb",
    "/docs/buttons" : "Buttons",
    "/docs/cards" : "Cards",
    "/docs/carousel" : "Carousel",
    "/docs/collapse" : "Collapse",
    "/docs/dropdowns" : "Dropdowns",
    "/docs/listgroup" : "List group",
    "/docs/modal" : "Modal",
    "/docs/navbar" : "Navbar",
    "/docs/navstabs" : "Navs and tabs",
    "/docs/offcanvas" : "Offcanvas",
    "/docs/pagination" : "Pagination",
    "/docs/placeholders" : "Placeholders",
    "/docs/popovers" : "Popovers",
    "/docs/progress" : "Progress",
    "/docs/spinners" : "Spinners",
    "/docs/toasts" : "Toasts",
    "/docs/bootstrap-icon" : "Bootstrap Icon",
    "/docs/flag-icon" : "Country Flag icon",
    "/docs/fontawesome-icon" : "Font awesome",
    "/docs/linear-icon" : "Simple line icon",
    "/docs/weather-icon" : "Weather icon",
    "/docs/apex" : "Apex chart",
    "/docs/peity" : "Peity chart",
    "/docs/bootstrap5-tags": "Bootstrap5 Tags",
    "/docs/datatables": "Datatables",
    "/docs/flatpickr": "Flatpickr",
    "/docs/inputmask": "Inputmask",
    "/docs/jsvectormap": "Jsvectormap",
    "/docs/sortablejs": "Sortable JS",
    "/docs/sweetalert2": "Sweetalert2",
    "/docs/tagify": "Tagify",
    "/docs/tiny-slider": "Tiny Slider",
    "/docs/toast-calendar": "Toast ui Calendar",
    "/docs/toast-editor": "Toast ui Editor",
    "/docs/widgets-basic-card": "Basic Card",
    "/docs/widgets-card-tiles": "Widgets Card Tiles",
    "/docs/widgets-card-tab": "Card Tab Design",
    "/pages/table": "Tables",
    "/pages/form": "Forms",
    "/pages/pricing": "Pricing Table",
    "/docs/index" : "Getting Started",
    "/docs/changelog": "Changelog",
    "/docs": "Docs",
  };